/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProblemSolutionRouteImport } from './routes/problem-solution'
import { Route as SchedulerRouteImport } from './routes/scheduler'
import { Route as ApiGeneratePlanRouteImport } from './routes/api/generate-plan'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemSolutionRoute = ProblemSolutionRouteImport.update({
  id: '/problem-solution',
  path: '/problem-solution',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulerRoute = SchedulerRouteImport.update({
  id: '/scheduler',
  path: '/scheduler',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeneratePlanRoute = ApiGeneratePlanRouteImport.update({
  id: '/api/generate-plan',
  path: '/api/generate-plan',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/problem-solution': typeof ProblemSolutionRoute
  '/scheduler': typeof SchedulerRoute
  '/api/generate-plan': typeof ApiGeneratePlanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/problem-solution': typeof ProblemSolutionRoute
  '/scheduler': typeof SchedulerRoute
  '/api/generate-plan': typeof ApiGeneratePlanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/problem-solution': typeof ProblemSolutionRoute
  '/scheduler': typeof SchedulerRoute
  '/api/generate-plan': typeof ApiGeneratePlanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/problem-solution' | '/scheduler' | '/api/generate-plan'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/problem-solution' | '/scheduler' | '/api/generate-plan'
  id:
    '__root__' | '/' | '/problem-solution' | '/scheduler' | '/api/generate-plan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProblemSolutionRoute: typeof ProblemSolutionRoute
  SchedulerRoute: typeof SchedulerRoute
  ApiGeneratePlanRoute: typeof ApiGeneratePlanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problem-solution': {
      id: '/problem-solution'
      path: '/problem-solution'
      fullPath: '/problem-solution'
      preLoaderRoute: typeof ProblemSolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduler': {
      id: '/scheduler'
      path: '/scheduler'
      fullPath: '/scheduler'
      preLoaderRoute: typeof SchedulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-plan': {
      id: '/api/generate-plan'
      path: '/api/generate-plan'
      fullPath: '/api/generate-plan'
      preLoaderRoute: typeof ApiGeneratePlanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProblemSolutionRoute: ProblemSolutionRoute,
  SchedulerRoute: SchedulerRoute,
  ApiGeneratePlanRoute: ApiGeneratePlanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
